article/urls.py
from django.conf.urls import *
# from views import home
# from views import detail
from . import views
urlpatterns = [
    url(r'^$',views.home,name='home'),
    url(r'^(?P<id>\d+)/$', views.detail, name='detail'),
    # url(r'^detail/$',home,name='detail'),
    url(r'^archives/$',  views.archives, name = 'archives'),
    url(r'^aboutme/$',  views.about_me, name = 'aboutme'),
    url(r'^tag(?P<tag>\w+)/$', views.search_tag, name = 'search_tag'),
    url(r'^search/$',views.blog_search, name = 'search'),
]

my_blog/urls.py
from django.conf.urls import *
from django.contrib import admin

urlpatterns = [
    url(r'^my/', include(admin.site.urls)),
    url(r'^',include('article.urls',namespace='article')),
]
 

article/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(u'标题',max_length = 100) #博客题目
    category = models.CharField(u'标签',max_length = 50, blank = True) #博客标签
    date_time = models.DateTimeField(u'信息发布日期',auto_now_add  = True) #博客日期
    content = models.TextField(u'信息简介',blank = True, null = True) #博客正文
    pub_time = models.DateTimeField(u'时间',null = True) #时间设置
    tel = models.IntegerField(u'电话',default=0)

    def __unicode__(self):
        return self.title

    class Meta: #按时间下降排序
        ordering = ['-date_time']


class side(models.Model):
    title = models.ForeignKey(Article)
    address = models.CharField(u'目的地',max_length = 100)
    price = models.IntegerField(u'路费',default=0)
    pub_time = models.DateTimeField(u'出发时间',null = True) #时间设置


article/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.http import HttpResponse
from article.models import Article
from datetime import datetime
from django.http import Http404

# Create your views here.
def home(request):
    posts = Article.objects.all()  #获取全部的Article对象
    paginator = Paginator(posts, 5) #每页显示两个
    page = request.GET.get('page')
    try :
        post_list = paginator.page(page)
    except PageNotAnInteger :
        post_list = paginator.page(1)
    except EmptyPage :
        post_list = paginator.paginator(paginator.num_pages)
    return render(request, 'home.html', {'post_list' : post_list})

def detail(request, id):
    try:
        post = Article.objects.get(id=str(id))
    except Article.DoesNotExist:
        raise Http404
    return render(request, 'post.html', {'post' : post})


def archives(request) :
    try:
        post_list = Article.objects.all()
    except Article.DoesNotExist :
        raise Http404
    return render(request, 'archives.html', {'post_list' : post_list, 
                                            'error' : False})

def about_me(request) :
    return render(request, 'aboutme.html')

def search_tag(request, tag) :
    try:
        post_list = Article.objects.filter(category__iexact = tag) #contains
    except Article.DoesNotExist :
        raise Http404
    return render(request, 'tag.html', {'post_list' : post_list})

def blog_search(request):
    if 's' in request.GET:
        s = request.GET['s']
        if not s:
            return render(request,'home.html')
        else:
            post_list = Article.objects.filter(title__icontains = s)
            if len(post_list) == 0 :
                return render(request,'archives.html', {'post_list' : post_list,
                                                    'error' : True})
            else :
                return render(request,'archives.html', {'post_list' : post_list,
                                                    'error' : False})
    return redirect('/')

templates/1.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <a href=>asd</a>{% url ' detail ' id %} {% block content %} {% endblock %}
</body>

</html>

templates/aboutme.html
{% extends "index.html" %} {% block content %}
<div class="posts">
    <p> About Me 正在建设中 </p>
</div>
<!-- /.blog-post -->
{% endblock %}

templates/archives.html
{% extends "index.html" %}{% block content %}
<div class="posts">
    {% if error %}
    <h2 class="post-title">没有相关文章题目</a>
    </h2>
    {% else %} {% for post in post_list %}
    <section class="post">
        <header class="post-header">
            <h2 class="post-title"><a href="{% url 'article:detail' id=post.id %}">{{ post.title }}</a></h2>

            <p class="post-meta">
                Time: <a class="post-author" href="#">{{ post.date_time |date:"Y /m /d"}}</a> <a class="post-category post-category-js" href="{% url 'article:search_tag' tag=post.category %}">{{ post.category }}</a>
            </p>
        </header>
    </section>
    {% endfor %} {% endif %}
</div>
<!-- /.blog-post -->
{% endblock %}

templates/home.html
{% extends "index.html" %} {% block content %}
<div class="posts">
    {% for post in post_list %}
    <section class="post">
        <header class="post-header">
            <h2 class="post-title">{{ post.title }}</h2>

            <p class="post-meta">
                Time: <a class="post-author" href="#">{{ post.date_time }}</a> <a class="post-category post-category-js" href="#">{{ post.category }}</a>
            </p>
        </header>

        <div class="post-description">
            <p>
                {{ post.content }}
            </p>
        </div>
    </section>
    {% endfor %}
</div>
<!-- /.blog-post -->
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://unpkg.com/purecss@0.6.2/build/pure-min.css" integrity="sha384-UQiGfs9ICog+LwheBSRCt1o5cbyKIHbwjWscjemyBMT9YCUMZffs6UqUTd0hObXD" crossorigin="anonymous">
    <!--[if lte IE 8]>
    <link rel="stylesheet" href="https://unpkg.com/purecss@0.6.2/build/grids-responsive-old-ie-min.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="https://unpkg.com/purecss@0.6.2/build/grids-responsive-min.css">
    <!--<![endif]-->
    <link rel="stylesheet" href="http://picturebag.qiniudn.com/blog.css">
</head>

<body>
    <div id="layout" class="pure-g">
        <div class="sidebar pure-u-1 pure-u-md-1-4">
            <div class="header">
                <h1 class="brand-title"><a href="{% url 'article:home' %}">xlelou</a></h1>
                <h2 class="brand-tagline">xlelou</h2>
                <nav class="nav">
                    <ul class="nav-list">
                        <li class="nav-item">
                            <a class="button-success pure-button" href="/">主页</a>
                        </li>
                        <li class="nav-item">
                            <a class="button-success pure-button" href="/">归档</a>
                        </li>
                        <li class="nav-item">
                            <a class="pure-button" href="https://github.com/Andrew-liu/my_blog_tutorial">Github</a>
                        </li>
                        <li class="nav-item">
                            <a class="button-error pure-button" href="http://weibo.com/dinosaurliu">Weibo</a>
                        </li>
                        <li class="nav-item">
                            <a class="button-success pure-button" href="/">专题</a>
                        </li>
                        <li>
                            <form class="pure-form" action="/search/" method="get">
                                <input class="pure-input-3-3" type="text" name="s" placeholder="search">
                            </form>
                        </li>
                        <li class="nav-item">
                            <a class="button-success pure-button" href="/">About Me</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>


        <div class="content pure-u-1 pure-u-md-3-4">
            <div>
                {% block content %} {% endblock %}
                <div class="footer">
                    <div class="pure-menu pure-menu-horizontal pure-menu-open">
                        <ul>
                            <li><a href="{% url 'article:aboutme'%}">About Me</a></li>
                            <li><a href="http://twitter.com/yuilibrary/">Twitter</a></li>
                            <li><a href="http://github.com/yahoo/pure/">GitHub</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

templates/post.html
{% extends "index.html" %} {% block content %}
<div class="posts">
    <section class="post">
        <header class="post-header">
            <h2 class="post-title">{{ post.title }}</h2>

            <p class="post-meta">
                Time: <a class="post-author" href="#">{{ post.date_time|date:"Y /m /d"}}</a> <a class="post-category post-category-js" href="#">{{ post.category }}</a>
            </p>
        </header>

        <div class="post-description">
            <p>
                {{ post.content }}
            </p>
            <p>
                {{ post.side.address }}
            </p>
            <p>{{ post.pub_time}}</p>
            <a href='tel:{{post.tel}}'>{{ post.tel}}</a>
        </div>
    </section>
</div>
<!-- /.blog-post -->
{% endblock %}

templates/tag.html
{% extends "index.html" %}{% block content %}
<div class="posts">
    {% for post in post_list %}
    <section class="post">
        <header class="post-header">
            <h2 class="post-title"><a href="{% url 'article:detail' id=post.id %}">{{ post.title }}</a></h2>

            <p class="post-meta">
                Time: <a class="post-author" href="#">{{ post.date_time |date:"Y M d"}}</a> <a class="post-category post-category-js" href="{% url 'article:search_tag' tag=post.category %}">{{ post.category|title }}</a>
            </p>
        </header>

        <div class="post-description">
            <p>
                {{ post.content|custom_markdown }}
            </p>
        </div>
        <a class="pure-button" href="{% url 'article:detail' id=post.id %}">Read More >>> </a>
    </section>
    {% endfor %}
</div>
<!-- /.blog-post -->
{% endblock %}